package com.smart.domain;

import java.util.Date;

public class Essay {

    private Long essayId;


    private String title;

    private String authorName;

    private String classify;


    private String tag;


    private Integer authorId;


    private Date createTime;


    private Long pageView;


    private Long greatNum;

    private String imgUrl;


    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.essay_id
     *
     * @return the value of essay.essay_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Long getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.essay_id
     *
     * @param essayId the value for essay.essay_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setEssayId(Long essayId) {
        this.essayId = essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.title
     *
     * @return the value of essay.title
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.title
     *
     * @param title the value for essay.title
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.classify
     *
     * @return the value of essay.classify
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getclassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.classify
     *
     * @param classify the value for essay.classify
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setclassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.tag
     *
     * @return the value of essay.tag
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.tag
     *
     * @param tag the value for essay.tag
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.author_id
     *
     * @return the value of essay.author_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Integer getauthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.author_id
     *
     * @param authorId the value for essay.author_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setauthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.create_time
     *
     * @return the value of essay.create_time
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.create_time
     *
     * @param createTime the value for essay.create_time
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.page_view
     *
     * @return the value of essay.page_view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Long getPageView() {
        return pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.page_view
     *
     * @param pageView the value for essay.page_view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setPageView(Long pageView) {
        this.pageView = pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.great_num
     *
     * @return the value of essay.great_num
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Long getGreatNum() {
        return greatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.great_num
     *
     * @param greatNum the value for essay.great_num
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setGreatNum(Long greatNum) {
        this.greatNum = greatNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column essay.content
     *
     * @return the value of essay.content
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column essay.content
     *
     * @param content the value for essay.content
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    @Override
    public String toString() {
        return "Essay{" +
                "essayId=" + essayId +
                ", title='" + title + '\'' +
                ", authorName='" + authorName + '\'' +
                ", classify='" + classify + '\'' +
                ", tag='" + tag + '\'' +
                ", authorId=" + authorId +
                ", createTime=" + createTime +
                ", pageView=" + pageView +
                ", greatNum=" + greatNum +
                ", imgUrl='" + imgUrl + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}