package com.smart.domain;

public class UserEssayCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_essay_collection.user_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_essay_collection.essay_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    private Long essayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_essay_collection.user_id
     *
     * @return the value of user_essay_collection.user_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_essay_collection.user_id
     *
     * @param userId the value for user_essay_collection.user_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_essay_collection.essay_id
     *
     * @return the value of user_essay_collection.essay_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Long getEssayId() {
        return essayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_essay_collection.essay_id
     *
     * @param essayId the value for user_essay_collection.essay_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setEssayId(Long essayId) {
        this.essayId = essayId;
    }
}