package com.smart.domain;

public class View {

    private Long viewId;


    private String classify;


    private String viewName;


    private String location;


    private String opentime;


    private String introducation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.view_id
     *
     * @return the value of view.view_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public Long getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.view_id
     *
     * @param viewId the value for view.view_id
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setViewId(Long viewId) {
        this.viewId = viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.classify
     *
     * @return the value of view.classify
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getclassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.classify
     *
     * @param classify the value for view.classify
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setclassify(String classify) {
        this.classify = classify == null ? null : classify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.view_name
     *
     * @return the value of view.view_name
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getViewName() {
        return viewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.view_name
     *
     * @param viewName the value for view.view_name
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setViewName(String viewName) {
        this.viewName = viewName == null ? null : viewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.location
     *
     * @return the value of view.location
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.location
     *
     * @param location the value for view.location
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.opentime
     *
     * @return the value of view.opentime
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getOpentime() {
        return opentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.opentime
     *
     * @param opentime the value for view.opentime
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setOpentime(String opentime) {
        this.opentime = opentime == null ? null : opentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column view.introducation
     *
     * @return the value of view.introducation
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public String getIntroducation() {
        return introducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column view.introducation
     *
     * @param introducation the value for view.introducation
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    public void setIntroducation(String introducation) {
        this.introducation = introducation == null ? null : introducation.trim();
    }
}