#这个地方写自己数据库连接配置，主要是密码，该文件不提交
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/garbage_sort?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: