server:
  port: 8004

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scenic_mark?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml