package com.smart.dao;

import com.smart.domain.Essay;
import java.util.List;

public interface EssayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int deleteByPrimaryKey(Long essayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int insert(Essay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    Essay selectByPrimaryKey(Long essayId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    List<Essay> selectAll();

    List<Essay> selectByAuthor(Integer authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table essay
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int updateByPrimaryKey(Essay record);

    List<Essay> selectByClassify(String classify);

    List<Essay> selectByTag(String tag);

    List<Essay> selectMyCollect(Integer userId);

    List<Essay> selectMyGreat(Integer userId);

    List<Essay> selectByKeyword(String keyword);
}