package com.smart.dao;

import com.smart.domain.UserEssayGreat;
import java.util.List;

public interface UserEssayGreatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_essay_great
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int insert(UserEssayGreat record);


    int delete(UserEssayGreat record);

    int check(UserEssayGreat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_essay_great
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    List<UserEssayGreat> selectAll();
}