package com.smart.dao;

import com.smart.domain.UserEssayCollection;
import java.util.List;

public interface UserEssayCollectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_essay_collection
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int insert(UserEssayCollection record);

    int delete(UserEssayCollection record);

    int check(UserEssayCollection record);


    List<UserEssayCollection> selectAll();



}