package com.smart.dao;

import com.smart.domain.View;
import java.util.List;

public interface ViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int deleteByPrimaryKey(Long viewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int insert(View record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    View selectByPrimaryKey(Long viewId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    List<View> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table view
     *
     * @mbg.generated Wed Oct 23 15:03:05 CST 2019
     */
    int updateByPrimaryKey(View record);

    List<View> selectFootprint(Integer userId);
}